# Generated by Django 3.2.6 on 2023-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
