# Generated by Django 3.2.6 on 2023-11-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20231116_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='token',
            field=models.CharField(max_length=280),
        ),
    ]
