# Generated by Django 3.2.6 on 2023-11-19 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_purchasedticket_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comp_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
