# Generated by Django 3.2.6 on 2023-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_event_comp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
